### ISSUE TITLE
DX10 Not Working (continuation)

### ISSUE THREAD

**Issue by mikeyhalla** [nefarius/Indicium-Supra#1]
**Issue continuation from: https://github.com/agrippa1994/DX9-Overlay-API/issues/37#issuecomment-322155048**

**My setup:** Visual Studio 2017 on Windows 10 x64. I followed your instructions to the letter in every README.md and all works perfectly except for a few DX10 Games that CAN be run in DX11 but I don't have hardware supported for anything higher than DX10. Its Nvidia 9800GT and its DX10 (not even 10.1 which may have something to do with it). I have it working great in all DX9 games.

**_Oh and you did press F11, right? This I should document_** 😆: LOL yeah, I found it in the code near the bottom. :D

**_You should find a log file generated at %TEMP%\Indicium-Supra.log what does it say?:_**

**DX9 game Working says: Direct3D11 [Error]:** Couldn't get handle to D3D11.dll
**Assassins Creed, being run in DX10 but has DX11 Support, Not working says: Direct3D11 [Error]:** Couldn't create D3D11 device

[Indicium-Supra (DX9 Working).log](https://pastebin.com/d20FX216)

[Indicium-Supra (DX10 Not Working).log](https://pastebin.com/scQ8FrkP)

**Comment by nefarius** [comment]
Plesse use something like pastebin for the log so formatting doesnt get lost, thanks.

**Comment by nefarius** [comment]
Sorry to bitch yet again but the newlines are lost in your paste ;P kinda hard to read.

**Comment by mikeyhalla** [comment]
I am so sorry. I know you have a lack of time and I am trying not to make things difficult.

[Indicium-Supra (DX9 Working).log](https://pastebin.com/d20FX216)

[Indicium-Supra (DX10 Not Working).log](https://pastebin.com/scQ8FrkP)

**Comment by agrippa1994** [comment]
Have you already tried the Markdown code embedding syntax?

**Comment by mikeyhalla** [comment]
Yes, I had done that in the first one and when I transitioned to new issue thread then I pasted in wrong stuff (Not MD but what shows after). Easy enough to just use Pastebin though. I am trying not to be difficult due to me really wanting to get this thing working. :D

**Comment by nefarius** [comment]
I'll be available in approx. 2 hours so don't think I opted out ;D

**Comment by nefarius** [comment]
Dumb question, AC3 is running for a few seconds then you inject, right? Cause the log says it can only detect DXv9.

**Comment by mikeyhalla** [comment]
its running for about 30 seconds then I inject. I have tried repeatedly... Bioshock Infinite is the same way.

**Comment by nefarius** [comment]
Can we continue on Discord maybe? I have a few ideas but it gets tedious via the GitHub issue tracker, if you don't mind.

**Comment by mikeyhalla** [comment]
That would be great! Thank you! :D

**Comment by nefarius** [comment]
[Come to me! Muhahaha!](https://discord.gg/xyqaKE)

**Comment by nefarius** [comment]
Fixed, lowered feature level to support GPUs which fall-back to DX10.
