### ISSUE TITLE
Manual Mapping not possible.

### ISSUE THREAD

**Issue by ShA-FR** [nefarius/Indicium-Supra#16]
Correct me if I'am wrong I actually want confirmation, since it has 2 output DLL's
I'm unable to do it.

Tried Jlibrary.
Xenos Injector.
GH Injector.

**Comment by nefarius** [comment]
What? I have no idea what you want, neither from the title nor from the body 😆

**Comment by xcxooxl** [comment]
I think he is referring to Inject the dll without using LoadLibrary in remote thread,
To avoid the injected module from being detected.

**Comment by nefarius** [comment]
There are different methods of foreign code injection documented thoroughly on the web but hiding the DLL(s) isn't within the scope of this project so you're on your own there.

**Comment by nefarius** [comment]
The core is designed as a dynamic library because of ease of use. It isn't trivial to statically link it with the currently required external dependencies.

**Comment by 0xGREG** [comment]
Sorry for pushing this, but if you look at Blackbone injector's source code, the part where it handles the CreateLdrRef flag will let you manual map this

**Comment by nefarius** [comment]
The library has been re-designed to be linked against statically since this issue was opened, so IDK if still relevant.

**Comment by 0xGREG** [comment]
He still needs to add his manual mapped dll to peb->ldr or the application will crash
