### ISSUE TITLE
Mouse/Keyboard input issue?

### ISSUE THREAD

**Issue by Adraesh** [nefarius/Indicium-Supra#18]
Hi!

Everything works fine:

- Building x64 => ok
- Injection => ok
- Rendering => ok

But mouse and or keyboard input are not working at all.

Also I can see in the log:

2019-04-14 11:22:44.122 HookWindowProc [Warning]: Couldn't create hook for GWLP_WNDPROC

but not sure if it's related.

Thanks!

**Comment by nefarius** [comment]
Yeah, mouse/keyboard hooking only works on "traditional" games using a message loop and a default window procedure to grab mouse inputs. It's not really something I have the time or motivation to implement as the samples are just a reference and there are way to many games out there for me to test.

Cheers

**Comment by Adraesh** [comment]
Hi @nefarius 

I am "re-openning" this topic just to get some insight/guideline how I could on my own first target the "window procedure" and "message loop type" used by the game I wish to interact with, and second iterate over your code in order to support it?

Thanks for your insights.

Best.

**Comment by nefarius** [comment]
Hi,

I recommend you hop on the Discord for that, we have like minded folks hanging around there, including myself 😉
