### ISSUE TITLE
 Documentation

### ISSUE THREAD

**Issue by DestroyerDarkNess** [nefarius/Indicium-Supra#20]
How does this work? . 
It works just like: [](https://github.com/agrippa1994/DX9-Overlay-API) ?

If so, is there any Wrapper for **.Net**?

**Comment by nefarius** [comment]
For the moment the samples folder is your best bet to get familiar how to use the framework. No, there's no dotnet wrapper, that would make little sense since the resulting library is native code running within a foreign process and should be lightning fast ☺️
