### ISSUE TITLE
Rehook swapchain if hook removed

### ISSUE THREAD

**Issue by 0xGREG** [nefarius/Indicium-Supra#21]
The game seems to create a new swapchain at times and that unhooks the overlay.

Is there any way to auto rehook like OBS does?

**Comment by nefarius** [comment]
Interesting, which game? In combination with other overlays?

**Comment by 0xGREG** [comment]
Well I experienced if Discord overlay is on this overlay might stop working and forcing it to rehook would be nice, any workaround that?

**Comment by nefarius** [comment]
Pardon the delay, I see, I will try that on my end. I assume it's not a disposed and new swapchain issue but the Discord hooking code overriding the hook Detours puts in place.

**Comment by nefarius** [comment]
Is it reproducible, happening regularly?

**Comment by 0xGREG** [comment]
happens like 25% of the time, can you suggest a solution that I could craft in the src

**Comment by nefarius** [comment]
New swapchain is less of an issue; the pointer will simply change, but the callbacks should still be invoked rather fine.

As for unhooking, hm. A lazy approach would be keeping reference to the original and the trampoline pointer after Detours hooks and periodically comparing them if they got changed "outside" of the framework and then re-hook.

**Comment by 0xGREG** [comment]
It seems like there is a new swapchain created or the swapchain eventually fails to hook

**Comment by nefarius** [comment]
Is it a D3D11 game?

**Comment by 0xGREG** [comment]
yes

**Comment by nefarius** [comment]
Sorry, I haven't had the capacity to further look into this 🙁

**Comment by 0xGREG** [comment]
It's fine, not a trivial issue just an interesting bug

**Comment by nefarius** [comment]
Sorry to let this become stale, currently I don't do any DX shenanigans whatsoever 🙁

**Comment by 0xGREG** [comment]
Issue is old and I found out that it was actually the other software's overlay bug, not mine. Sorry for the misunderstanding.
