### ISSUE TITLE
Complete black screen lockup or strange behavior in true fullscreen games

### ISSUE THREAD

**Issue by s4e-tom** [nefarius/Indicium-Supra#4]
Hello,

I'm currently working on a project for the Unreal Engine 3 game Guilty Gear Xrd -REVELATOR-. The goal is to integrate a mod tool into an overlay.

I built Indicium-Supra and Indicium-ImGui.Plugin and injected Indicium-Supra with your Injector project. Works as intended when the game is windowed.

However when the game is in fullscreen (true fullscreen, ie not borderless-windowed and win10's fullscreen optimization disabled), the game turns black and seems frozen. It can also be a bit difficult to kill the process in that situation, because the frozen black fullscreen game keeps the focus and seems always on top.

I also tried to inject when game is windowed, then go fullscreen, but the result is the same.

Some other games don't lock up and seem to work fine in true fullscreen (Arcana Heart 3), but they still have the strange always on top behavior, and thus can't be alt-tabbed.

If you have any tips on this issue or need more details, please let me know.

Thanks,
Tom.

**Comment by nefarius** [comment]
Heya,

well, a bit more details would be helpful like: architecture, DX version, does it misbehave with one of the sample plugins or with your own etc.

**Comment by s4e-tom** [comment]
Hello,

Thank you for your answer. Here are some details.
32bit Injector from https://github.com/nefarius/Injector/releases/latest
32bit Indicium-Supra built from source
32bit Indicium-ImGui.Plugin built from source
Guilty Gear Xrd is 32bit and uses DX9
Windows 10.0.16299

Windowed
![image](https://user-images.githubusercontent.com/3964857/38778031-94f81530-40b2-11e8-852c-a1981dc635ec.png)

Fullscreen
![image](https://user-images.githubusercontent.com/3964857/38778060-267a4028-40b3-11e8-94ec-3e31172bca17.png)


Misbehaves with the Indicium-ImGui sample plugin

**Comment by nefarius** [comment]
Ah you documented that case already. I have an idea what might be the issue and possible solution. Will test once I'm back at my PC in like one or two hours.

**Comment by s4e-tom** [comment]
Yes, here are some other scenarios I have tried:

- Injecting into full-screen (alt tabbed), or switching into fullscreen after injection, give the same issue.
- Injecting into full-screen, not alt-tabbed by delaying the injection with `timeout 10 >nul && Injector --inject --module-name Indicium-Supra.dll --process-name GuiltyGearXrd.exe` , does not lock up the game, however in that scenario it is not possible to bring up the overlay and the game has an always on top behavior (can't be alt tabbed back to desktop).

Additionally, when injected into windowed, changing the window size from the game resolution settings locks up the game.
![image](https://user-images.githubusercontent.com/3964857/38778541-580faea4-40bb-11e8-8432-9dd691927758.png)

**Comment by nefarius** [comment]
Then I know what's happening: in my samples I got lazy and didn't implement the `Reset` callback. You wanna hop on my Discord to have a discussion and some tests with that?

**Comment by s4e-tom** [comment]
Yes, gladly
